# Generated by Django 2.1 on 2018-09-10 17:41

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator(message='Provide a valid email')])),
                ('username', models.EmailField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.EmailValidator(message='Provide a valid email')])),
                ('password', models.CharField(max_length=100)),
                ('jwt_secret', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
