# Generated by Django 2.1 on 2018-09-10 18:18

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('coordinate_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=10, default=Decimal('0.0000'), max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=10, default=Decimal('0.0000'), max_digits=20)),
            ],
        ),
    ]
