# Generated by Django 2.1 on 2018-09-10 18:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resturant',
            fields=[
                ('resturant_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resturant_name', models.CharField(max_length=200)),
                ('coordinate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resturants.Coordinate')),
            ],
        ),
    ]
