# Generated by Django 2.1 on 2018-09-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0002_resturant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
